version: "3.7"

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: FE
    ports:
      - "8888:80"
    networks:
      - conditional-pipeline

networks:
  conditional-pipeline:
    driver: bridge
    name: conditional-pipeline
    external: true