version: "3.7"

services:
  main:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: main-repo
    ports:
      - 8080:5000
    networks:
      - conditional-pipeline

networks:
  conditional-pipeline:
    driver: bridge
    name: conditional-pipeline
    external: true